# Generated by Django 4.2.5 on 2023-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregistration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
