# Generated by Django 4.2.5 on 2023-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
