# Generated by Django 4.2.5 on 2023-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=100)),
                ('fea_img', models.ImageField(upload_to='Features/')),
            ],
        ),
    ]
